### PR TITLE
Don't use world frame in moveit

### PR DESCRIPTION
**Pull request by bjsowa**
#10

### CODE REVIEW

**Comment by swinterbotix** [comment]
@bjsowa,

I do agree with your changes to remove the 'fixed' joint in the SRDFs from all the robots. Otherwise, if someone wanted to fix the base_link of the robot arm to a frame other than world, they would be forced to call the name of that joint 'fixed' instead of something more informative. Even without that reason, the 'fixed' joint isn't necessary for the 'interbotix_arm' planning group to function properly.

I don't see the benefit though of making the fixed frame in Rviz equivalent to `/<robot_name>/base_link`. Especially for a mobile robot, if Rviz's fixed frame was set to the arm's base_link frame, then the 2D grid will be located at the arm's base instead of the bottom of the mobile platform - which would look strange.

**Comment by swinterbotix** [comment]
I've pushed another update that got rid of the 'fixed' joint issue in the SRDFs. I've also made it easier to integrate a mobile robot with the arm by allowing you to specify your custom urdf.xacro file via the `external_urdf_loc` argument. Additionally, you can add a custom srdf.xacro containing additional 'disable collision' tags between the robot arm and your mobile base using the 'external_srdf_loc' argument. The only other thing I think you will have to do when you create your own launch file is create a joint_state_publisher where you can feed in the joint states from the interbotix_sdk and your mobile base. This should publish to `/<robot_name>/joint_states`. In order to do this, you will have to remap the joint states coming from the interbotix_sdk node to something like `/<robot_name>/arm/joint_states`.

**Comment by bjsowa** [comment]
> I don't see the benefit though of making the fixed frame in Rviz equivalent to /<robot_name>/base_link.

The benefit I see is that I can now fix the arm's `base_link` to the robot platform (thus getting rid of the `world` frame) and still be able to launch the moveit with the fixed frame set to the link name that is guaranteed to exist on the TF tree.

> Especially for a mobile robot, if Rviz's fixed frame was set to the arm's base_link frame, then the 2D grid will be located at the arm's base instead of the bottom of the mobile platform - which would look strange.

How is this worse than setting it to the `world` frame? As far as I know, the `world` frame will be either fixed to the arm's `base_link` or won't exist at all.

Thanks for the update. I'll check if the additional arguments for extending the urdf and srdf models are applicable in my case.

**Comment by swinterbotix** [comment]
The way I see it, the `world` frame will always exist - either attached to the arm's base_link or attached by some transform to the base_footprint frame of the mobile base (in the latter case, this transform will either be published by a static transform publisher or from an odometry source depending on if the mobile base is being used).

**Comment by bjsowa** [comment]
I still don't see a point in forcing the use of the `world` frame. Considering the robot publishes the transform from the odometry source:
1. The odometry origin frame has to be named `world` which is not even consistent with [REP105](https://www.ros.org/reps/rep-0105.html).
2. The robot would move from the origin point in RViz which, I think, is not desired when performing the arm trajectory planning.

**Comment by swinterbotix** [comment]
I see your point. That said, I think it would be better to make Rviz's fixed frame a launch file argument instead of limiting it to `/<robot_name>/base_link`. That way, if using a mobile base, you could set it to the base link frame of the mobile base instead of it being stuck at the base link frame of the arm. By default, I think it should still be `world` to keep the consistency between MoveIt and Gazebo and eliminate the KDL inertia warning.

**Pull request closed without merging**
